### ISSUE TITLE
Cannot log in (asopo.webuntis.com instead of mese.webuntis.com)

### ISSUE THREAD

**Issue by enteryournamehere** [tuesd4y/node-webuntis#3]
Hello,

I am trying to use this API, however, I can't get it to work.
Your API interface requests https://mese.webuntis.com/WebUntis/jsonrpc.do?school=<school\>, but for my school, this returns: `{"jsonrpc":"2.0","id":"error","error":{"message":"invalid schoolname","code":-8500}}`. I think this is because my school uses asopo.webuntis.com/... instead of mese.webuntis.com/... (I don't know why or what is the difference).
So I tried to request https://asopo.webuntis.com/WebUntis/jsonrpc.do?school=<school\>, but this returns `{"jsonrpc":"2.0","id":null,"error":{"code":-32700,"message":"Parse error: No content to map due to end-of-input\n at [Source: org.apache.catalina.connector.CoyoteInputStream@11a4cb70; line: 1, column: 0]"}}`. Do you know if it is possible to add support for schools that use asopo.webuntis.com/..., or is this not possible due to a limitation on WebUntis' side?

(When I just enter my school name + login credentials in your api, it gives the error "no sessionId returned")

Thanks in advance for a response, and I'd love to use your API, it looks really great :)

**Comment by tuesd4y** [comment]
Hi, 

As far as I know, there is more or less no official documentation for the UNTIS api, so what this project provides is just a wrapper for the API-version used at my school. 

I'm pretty sure it'd be possible to add support for endpoints other than mese.webuntis.com, but unfortunately i don't have access to any other endpoints. Maybe you could ask any of your teachers if they have any kind of documentation for webuntis?

On most schools there also exist test user accounts, if you could provide me with a test login i might as well be able to fix your problem, since there is may also be some kind of encoding problem. 

Does you school, by any chance have a name including a dash?

I hope I'll be able to help you ;)

**Comment by enteryournamehere** [comment]
Hey,

Please try school name "--redacted--", username "--redacted--" and no password as test login. As you can see the school name does not have a dash or any other special character.

In the Untis Mobile app, there's a demo school with domain "kalliope.webuntis.com", username "hero", but it doesn't show the password, maybe you can get that from the app and use it as another domain/test account.

(It still gives the error "no sessionId returned" after DavidM's commits)

Thanks!

**Comment by enteryournamehere** [comment]
On webuntis, when I go to the untis mobile link settings, it shows an api key, could this be of any use?

**Comment by chromey** [comment]
On a related note: while the docs mention support for other servers, so far this is only available on the master branch - the latest version published to npm is v0.13 from 7 months ago. Once I switched my dependency to the master branch, I was successfully able to connect to a school on the "tritone" server. Thanks for your efforts, @tuesd4y

**Comment by tuesd4y** [comment]
You're welcome @chromey , I totally forgot pushing the changes to the npm registry, but I'll do that as soon as i can, which will be in little more than a week.

@enteryournamehere did you use the library version at the master branch or from npm?

**Comment by enteryournamehere** [comment]
Oooh I might have use the version on npm; will check tomorrow. Thanks!

**Comment by enteryournamehere** [comment]
Working now, sorry for the confusion! Thanks so much!!
